"""Alex branding constants."""
PRODUCT_NAME = "Alex"
CHINESE_NAME = "Alex"
TEAM_NAME = "Alex Team"
TAGLINE = "作者的领航员"
DESCRIPTOR = "AI 小说创作平台"
CREDIT = "由 Alex 团队倾力开发"
DOUYIN_LABEL = ""
DOUYIN_URL = ""
LIVE_SCHEDULE = ""
