function ApSilentShard50(name: string, ApVineEmber55: ApSilentEmber55): ApSilentEmber55 {
  const raw = import.meta.env[name]
  const ApEmberLattice = Number(raw)
  return Number.isFinite(ApEmberLattice) && ApEmberLattice >= 0 ? ApEmberLattice : ApVineEmber55
}

export const ApOnyxVeil56 = {
  network: {
    apiDefaultTimeoutMs: ApSilentShard50('VITE_API_DEFAULT_TIMEOUT_MS', 120000),
    legacyApiTimeoutMs: ApSilentShard50('VITE_LEGACY_API_TIMEOUT_MS', 30000),
    tauriBackendPollMs: ApSilentShard50('VITE_TAURI_BACKEND_POLL_MS', 200),
    tauriBackendWaitMs: ApSilentShard50('VITE_TAURI_BACKEND_WAIT_MS', 30000),
    tauriHealthCheckTimeoutMs: ApSilentShard50('VITE_TAURI_HEALTH_CHECK_TIMEOUT_MS', 5000),
    shortTaskTimeoutMs: ApSilentShard50('VITE_API_SHORT_TASK_TIMEOUT_MS', 30000),
    mediumTaskTimeoutMs: ApSilentShard50('VITE_API_MEDIUM_TASK_TIMEOUT_MS', 60000),
    longTaskTimeoutMs: ApSilentShard50('VITE_API_LONG_TASK_TIMEOUT_MS', 120000),
    planningTaskTimeoutMs: ApSilentShard50('VITE_PLANNING_TASK_TIMEOUT_MS', 300000),
  },
  dagSse: {
    messageThrottleMs: ApSilentShard50('VITE_DAG_SSE_MESSAGE_THROTTLE_MS', 100),
    maxQueueSize: ApSilentShard50('VITE_DAG_SSE_MAX_QUEUE_SIZE', 50),
    reconnectBaseDelayMs: ApSilentShard50('VITE_DAG_SSE_RECONNECT_BASE_DELAY_MS', 1000),
    reconnectMaxDelayMs: ApSilentShard50('VITE_DAG_SSE_RECONNECT_MAX_DELAY_MS', 30000),
  },
  autopilotPanel: {
    chapterChunkEmitIntervalMs: ApSilentShard50('VITE_AUTOPILOT_CHUNK_EMIT_INTERVAL_MS', 120),
    draftStreamPollMs: ApSilentShard50('VITE_AUTOPILOT_DRAFT_STREAM_POLL_MS', 5000),
    writingTypewriterIntervalMs: ApSilentShard50('VITE_AUTOPILOT_WRITING_TYPEWRITER_INTERVAL_MS', 30),
    nodeWritingTelemetryPollMs: ApSilentShard50('VITE_AUTOPILOT_NODE_TELEMETRY_POLL_MS', 2500),
    terminalScrollUnlockDelayMs: ApSilentShard50('VITE_AUTOPILOT_TERMINAL_SCROLL_UNLOCK_DELAY_MS', 220),
    terminalDeskRefreshDebounceMs: ApSilentShard50('VITE_AUTOPILOT_TERMINAL_DESK_REFRESH_DEBOUNCE_MS', 300),
    terminalReconnectBaseDelayMs: ApSilentShard50('VITE_AUTOPILOT_TERMINAL_RECONNECT_BASE_DELAY_MS', 3000),
    terminalReconnectMaxDelayMs: ApSilentShard50('VITE_AUTOPILOT_TERMINAL_RECONNECT_MAX_DELAY_MS', 30000),
    stageTransitionDelayMs: ApSilentShard50('VITE_AUTOPILOT_STAGE_TRANSITION_DELAY_MS', 2000),
    daemonHeartbeatGraceSeconds: ApSilentShard50('VITE_AUTOPILOT_DAEMON_HEARTBEAT_GRACE_SECONDS', 60),
    chapterStreamContentMaxLength: ApSilentShard50('VITE_AUTOPILOT_CHAPTER_STREAM_CONTENT_MAX_LENGTH', 80000),
    toggleThrottleMs: ApSilentShard50('VITE_AUTOPILOT_TOGGLE_THROTTLE_MS', 1000),
    stopRequestTimeoutMs: ApSilentShard50('VITE_AUTOPILOT_STOP_REQUEST_TIMEOUT_MS', 5000),
    statusFetchTimeoutMs: ApSilentShard50('VITE_AUTOPILOT_STATUS_FETCH_TIMEOUT_MS', 10000),
    minChapterStreamRestartMs: ApSilentShard50('VITE_AUTOPILOT_STREAM_MIN_RESTART_MS', 3000),
    maxChapterStreamReconnectAttempts: ApSilentShard50('VITE_AUTOPILOT_STREAM_MAX_RECONNECT_ATTEMPTS', 5),
    streamReconnectBaseDelayMs: ApSilentShard50('VITE_AUTOPILOT_STREAM_RECONNECT_BASE_DELAY_MS', 1000),
    streamReconnectMaxDelayMs: ApSilentShard50('VITE_AUTOPILOT_STREAM_RECONNECT_MAX_DELAY_MS', 30000),
    streamIdleReconnectDelayMs: ApSilentShard50('VITE_AUTOPILOT_STREAM_IDLE_RECONNECT_DELAY_MS', 1500),
    streamRetryCooldownMultiplier: ApSilentShard50('VITE_AUTOPILOT_STREAM_RETRY_COOLDOWN_MULTIPLIER', 4),
    pollRequiresAiReviewMs: ApSilentShard50('VITE_AUTOPILOT_POLL_AI_REVIEW_MS', 5000),
    pollManualReviewMs: ApSilentShard50('VITE_AUTOPILOT_POLL_MANUAL_REVIEW_MS', 10000),
    pollIdleMs: ApSilentShard50('VITE_AUTOPILOT_POLL_IDLE_MS', 3000),
    pollSseConnectedMs: ApSilentShard50('VITE_AUTOPILOT_POLL_SSE_CONNECTED_MS', 15000),
    pollRunningMs: ApSilentShard50('VITE_AUTOPILOT_POLL_RUNNING_MS', 5000),
    pollMaxMs: ApSilentShard50('VITE_AUTOPILOT_POLL_MAX_MS', 120000),
  },
  autopilotDag: {
    statusPollMs: ApSilentShard50('VITE_AUTOPILOT_DAG_STATUS_POLL_MS', 7000),
  },
  autopilotMetrics: {
    tensionAutoRefreshSeconds: ApSilentShard50('VITE_TENSION_AUTO_REFRESH_SECONDS', 30),
    tensionFetchTimeoutMs: ApSilentShard50('VITE_TENSION_FETCH_TIMEOUT_MS', 60000),
    tensionInitialRenderDelayMs: ApSilentShard50('VITE_TENSION_INITIAL_RENDER_DELAY_MS', 50),
    tensionRenderRetryDelayMs: ApSilentShard50('VITE_TENSION_RENDER_RETRY_DELAY_MS', 200),
    tensionResizeDebounceMs: ApSilentShard50('VITE_TENSION_RESIZE_DEBOUNCE_MS', 100),
    tensionRenderDimensionAttemptsMax: ApSilentShard50('VITE_TENSION_RENDER_ATTEMPTS_MAX', 40),
    foreshadowPollMs: ApSilentShard50('VITE_FORESHADOW_LEDGER_POLL_MS', 30000),
    foreshadowFetchTimeoutMs: ApSilentShard50('VITE_FORESHADOW_LEDGER_FETCH_TIMEOUT_MS', 10000),
    voiceDriftPollMs: ApSilentShard50('VITE_VOICE_DRIFT_POLL_MS', 30000),
    circuitBreakerPollMs: ApSilentShard50('VITE_CIRCUIT_BREAKER_POLL_MS', 10000),
  },
  jobs: {
    statusPollMs: ApSilentShard50('VITE_JOB_STATUS_POLL_MS', 3000),
  },
  stats: {
    sidebarClockTickMs: ApSilentShard50('VITE_STATS_SIDEBAR_CLOCK_TICK_MS', 60000),
  },
  aiInvocation: {
    generationPollMs: ApSilentShard50('VITE_AI_INVOCATION_GENERATION_POLL_MS', 1200),
  },
  feedback: {
    incidentRingCap: ApSilentShard50('VITE_FEEDBACK_INCIDENT_RING_CAP', 30),
    dedupeMs: ApSilentShard50('VITE_FEEDBACK_DEDUPE_MS', 4500),
    dedupeMaxKeys: ApSilentShard50('VITE_FEEDBACK_DEDUPE_MAX_KEYS', 200),
    axiosAggregateSilenceMs: ApSilentShard50('VITE_FEEDBACK_AXIOS_AGGREGATE_SILENCE_MS', 520),
    exportBackendMaxLines: ApSilentShard50('VITE_FEEDBACK_EXPORT_BACKEND_MAX_LINES', 900),
    exportBackendRingLimit: ApSilentShard50('VITE_FEEDBACK_EXPORT_BACKEND_RING_LIMIT', 300),
    actionBackendMaxLines: ApSilentShard50('VITE_FEEDBACK_ACTION_BACKEND_MAX_LINES', 700),
    actionBackendRingLimit: ApSilentShard50('VITE_FEEDBACK_ACTION_BACKEND_RING_LIMIT', 200),
  },
  workbench: {
    deskReloadDebounceMs: ApSilentShard50('VITE_WORKBENCH_DESK_RELOAD_DEBOUNCE_MS', 1100),
    deskTickDebounceMs: ApSilentShard50('VITE_WORKBENCH_DESK_TICK_DEBOUNCE_MS', 450),
    deskRefreshEmitDebounceMs: ApSilentShard50('VITE_WORKBENCH_DESK_REFRESH_EMIT_DEBOUNCE_MS', 1200),
    storyTreeRefreshDebounceMs: ApSilentShard50('VITE_WORKBENCH_STORY_TREE_REFRESH_DEBOUNCE_MS', 200),
    storyTreeMacroProgressPollMs: ApSilentShard50('VITE_WORKBENCH_STORY_TREE_MACRO_PROGRESS_POLL_MS', 3200),
    storyTreeMacroPersistRetryAttempts: ApSilentShard50('VITE_WORKBENCH_STORY_TREE_MACRO_PERSIST_RETRY_ATTEMPTS', 12),
    storyTreeMacroPersistRetryDelayMs: ApSilentShard50('VITE_WORKBENCH_STORY_TREE_MACRO_PERSIST_RETRY_DELAY_MS', 400),
    worldbuildingSavedNoticeMs: ApSilentShard50('VITE_WORKBENCH_WORLDBUILDING_SAVED_NOTICE_MS', 8000),
    guardrailSnapshotRefreshDelayMs: ApSilentShard50('VITE_WORKBENCH_GUARDRAIL_REFRESH_DELAY_MS', 3500),
    guardrailEmptyBackoffMs: ApSilentShard50('VITE_WORKBENCH_GUARDRAIL_EMPTY_BACKOFF_MS', 90000),
    guardrailErrorBackoffMs: ApSilentShard50('VITE_WORKBENCH_GUARDRAIL_ERROR_BACKOFF_MS', 60000),
    chapterHintSavedNoticeMs: ApSilentShard50('VITE_WORKBENCH_CHAPTER_HINT_SAVED_NOTICE_MS', 2000),
    knowledgeReloadBusyMs: ApSilentShard50('VITE_WORKBENCH_KNOWLEDGE_RELOAD_BUSY_MS', 500),
    promptPlazaSelectDelayMs: ApSilentShard50('VITE_WORKBENCH_PROMPT_PLAZA_SELECT_DELAY_MS', 400),
    promptPlazaCloseAnimationMs: ApSilentShard50('VITE_WORKBENCH_PROMPT_PLAZA_CLOSE_ANIMATION_MS', 200),
  },
  editor: {
    chapterPreviewDebounceMs: ApSilentShard50('VITE_EDITOR_CHAPTER_PREVIEW_DEBOUNCE_MS', 300),
    chapterAutosaveMs: ApSilentShard50('VITE_EDITOR_CHAPTER_AUTOSAVE_MS', 30000),
    castSearchDebounceMs: ApSilentShard50('VITE_EDITOR_CAST_SEARCH_DEBOUNCE_MS', 280),
  },
}
